name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clang-Format Check (Bash)
      shell: bash
      run: |
        FILES=$(find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cc" \) -not -path "./out/*")
        for file in $FILES; do
          clang-format --dry-run --Werror "$file"
        done

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      shell: bash

    - name: Configure with CMake
      run: cmake --preset=vs2022-windows -B out -S .

    - name: Debug VCPKG_ROOT
      run: |
        echo "VCPKG_ROOT is set to $VCPKG_ROOT"
        ls -l $VCPKG_ROOT
      shell: bash
    
    - name: Build
      run: cmake --build --preset vs2022-windows-release
      shell: bash
